### PR TITLE
Add JDK 11 Builds

### PR DESCRIPTION
**Pull request by 123Haynes**
This commit adds build jobs for JDK 11 to CircleCI.

based on https://github.com/akihyro/orika-spring-boot-starter/pull/10

### CODE REVIEW

**Comment by 123Haynes** [comment]
these ci failures are really random 😢 
I didn't even touch the code, but build jobs that have not been affected at all suddenly fail...

**Comment by 123Haynes** [comment]
failing tests are fixed with #10.

Please merge that one first :)

**Comment by akihyro** [comment]
Sorry for the late reply.

Thanks for contributing!
Looks good to me 👍

**Comment by akihyro** [comment]
v1.9.0 has been released 🎉 

https://github.com/akihyro/orika-spring-boot-starter/releases/tag/v1.9.0

**Pull request merged**
